import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    marginTop: '20%',
    paddingHorizontal: 20,
  },
  miniMain: {
    justifyContent: 'space-between',
    gap: 10,
    flexDirection: 'row',
  },

  loginStyle: {
    backgroundColor: '#005AFF14',
    width: 147,
    height: 32,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loginText: {
    backgroundColor: 'accent alpha/3',
    color: '#0038DCD8',
    fontSize: 14,
    fontWeight: 500,
    lineHeight: 20,
    letterSpacing: 0,
  },
  accountContainer: {
    alignItems: 'center',
  },
  accountText: {
    color: 'black',
    paddingBottom: 20,
    fontWeight: 'bold',
    fontSize: 20,
    alignSelf: 'flex-start',
    marginTop: 20,
  },
  emailText: {
    alignSelf: 'flex-start',
  },
  emailInput: {
    height: 40,
    borderColor: 'gray',
    borderWidth: 1,
    width: '100%',
    marginBottom: 30,
    borderRadius: 10,
    paddingHorizontal: 10,
    marginTop: 10,
  },
  passwordText: {
    fontSize: 14,
    textAlign: 'left',
    alignSelf: 'flex-start',
    marginBottom: 15,
    color: 'black',
    fontWeight: 'bold',
  },
  passwordInput: {
    height: 40,
    borderColor: 'gray',
    borderWidth: 1,
    width: '100%',
    paddingHorizontal: 10,
    borderRadius: 10,
  },
  emailContinue: {
    width: '100%',
  },
  forgotText: {
    color: 'black',
    alignSelf: 'flex-end',
    fontWeight: 'bold',
    marginTop: '5%',
  },
  touchGoogle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    width: '100%',
    marginTop: '10%',
    backgroundColor: 'white',
    paddingVertical: 10,
    paddingHorizontal: 30,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'lightgrey',
  },
  continueText: {
    color: 'black',
    fontWeight: 'bold',
    fontSize: 14,
    height: 23,
    textAlign: 'center',
  },
  touchApple: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    marginTop: '10%',
    backgroundColor: 'white',
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'lightgrey',
    gap: 10,
  },
  appleText: {
    color: 'black',
    fontWeight: 'bold',
    fontSize: 14,
    height: 16,
    textAlign: 'center',
  },
  imageView: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  titleStyle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: 'black',
  },
  imageStyle: {
    height: 32,
    width: '20%',
    objectFit: 'contain',
  },
  imageStyle1: {
    height: 25,
    width: '10%',
    objectFit: 'contain',
    justifyContent: 'center',
    alignItems: 'center',
  },
  lastText: {
    marginTop: '10%',
    color: 'black',
  },
  lastText1: {
    color: 'black',
  },
  line: {
    borderWidth: 1,
    width: '43%',
    borderColor: '#000B3618',
  },

  container: {
    flexDirection: 'row',
    marginTop: '10%',
    gap: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  lineApple: {
    flexDirection: 'row',
    marginTop: '10%',
  },
  lineApple1: {
    borderWidth: 1,
    width: '100%',
    borderColor: '#000B3618',
  },
  underApple: {
    marginTop: '5%',
  },
});
